# Generated by Django 4.2.4 on 2023-09-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                ("is_customer", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
