# Generated by Django 4.2.4 on 2023-09-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="storeuser",
            name="last_name",
        ),
        migrations.AddField(
            model_name="storeuser",
            name="username",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
