# Generated by Django 4.2.4 on 2023-09-04 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0003_storeusermanager"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StoreUserManager",
        ),
    ]
