# Generated by Django 4.2.4 on 2023-09-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0007_alter_storeuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeuser",
            name="username",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
