# Generated by Django 4.2.4 on 2023-09-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0009_alter_storeuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storeuser",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
