# Generated by Django 4.2.4 on 2023-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0011_remove_storeuser_username_storeuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeuser",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
