# Generated by Django 4.2.4 on 2023-09-04 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0012_storeuser_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storeuser",
            old_name="is_active",
            new_name="is_email_confirmed",
        ),
    ]
