# Generated by Django 4.2.4 on 2023-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0013_rename_is_active_storeuser_is_email_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="storeuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
