# Generated by Django 4.2.4 on 2023-09-06 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0014_storeuser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storeuser",
            name="username",
        ),
    ]
